#ifndef CERTIFICATES_H
#define CERTIFICATES_H

#include <Arduino.h>

// Root CA Certificate (used to verify the MQTT broker's certificate)
// Generated by certificate_generator.py
const char* const ca_certificate PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIC9DCCAdygAwIBAgIUQFYnxRGw0gzhZKIuVtPDWzaaX5swDQYJKoZIhvcNAQEL
BQAwGjEYMBYGA1UEAwwPVm90aW5nU3lzdGVtLUNBMB4XDTI2MDYwMzE4MTgzOFoX
DTM2MDUzMTE4MTgzOFowGjEYMBYGA1UEAwwPVm90aW5nU3lzdGVtLUNBMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzackPL05IldQAayRXk3yznJZXiMA
Y4ibiXC+NI1FLg0CLb+7bbOAsoM0lFT+wQJX+k854vRdie4ZytqyOtlzqBipiVqg
BzmXQ9tWZ8VjbaBaVgivGYXWsKeEl1mTs9p99hGqmK6XD/YU0eRaYaNKWw/bi5YG
MlXF+u3UFJvK6tTJIf2+YQKOIr3+LKlHbBP3F36JDVJo/JoBzAvAAh9TU1KK2vM/
qUie/qNxqeqnnc4MRuFgbW1Xi2vwLN7GSC8jY9knmMljepNeCaP5Pu6nSyT+oH5u
pWo1ijYUPJbht8H66/cuaEfz1iC+gd8fCpd8ao//p03DUypMoEEKGHLyDwIDAQAB
ozIwMDAdBgNVHQ4EFgQUHWb2webIuvkCb6t5p4x4EKtv/9cwDwYDVR0TAQH/BAUw
AwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAbutLyDVPyzcXIryZiCSuwTrGVwd2Lxhm
gZhL0hdcZd03ePBzgKwyHHPqnJyuGaiMITCcvlr+PaQrs1bv9TpCBvY5nx7FkJB6
9u2hjviR7bGRR/4wNlKh77JyS14AsZxM5tIddmT2u+gC2smNSdelllJffvVp4Syf
dZ6zlIcesNOiksetSBNuHJMaR8gAV/ZqeGQFjM1qrrT5rbR6+hf9qAtdp0W7Zx0e
Gx63/nFdRANR1j71VWcssamTcqFsf+/39yrVLzfJoV9BnylQcsQRt4eHOXL5O0Ia
Naqk2thydtV4wHgKrbpcsXhCW4kkCBQ+wzMUjb2U5YAYqZ5JvDnw4A==
-----END CERTIFICATE-----
)EOF";

// Client Certificate (used for client authentication by the broker)
// Replace with the contents of voting_system/security/certificates/client.crt if MQTT_USE_TLS is true
const char* const client_certificate PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
// INSERT YOUR CLIENT CERTIFICATE HERE
-----END CERTIFICATE-----
)EOF";

// Client Private Key (used for client authentication by the broker)
// Replace with the contents of voting_system/security/certificates/client.key if MQTT_USE_TLS is true
const char* const client_key PROGMEM = R"EOF(
-----BEGIN PRIVATE KEY-----
// INSERT YOUR CLIENT PRIVATE KEY HERE
-----END PRIVATE KEY-----
)EOF";

#endif // CERTIFICATES_H
