# IoT Secure Smart Voting System Mosquitto Configuration

persistence true
persistence_location ./mqtt/data/

log_dest file ./mqtt/log/mosquitto.log
log_type all
connection_messages true

allow_anonymous true

listener 1883
protocol mqtt

listener 8883
protocol mqtt
cafile ./security/certificates/ca.crt
certfile ./security/certificates/server.crt
keyfile ./security/certificates/server.key
require_certificate false

retain_available false
